#ifndef SYSTEM_ERRORS_H
#define SYSTEM_ERRORS_H

typedef enum {
  ERROR_SD_CARD,
  ERROR_FILE,
  ERROR_ADC_INIT,
  ERROR_ADC_CONFIG,
  ERROR_REGULATOR_VOLTAGE_SCALE,
  ERROR_USB_VOLTAGE_SCALE,
  ERROR_RCC_OSC_CONFIG,
  ERROR_RCC_CLK_CONFIG,
  ERROR_PLL_CLK_CONFIG,
  ERROR_PERIPH_CLK_CONFIG,
  ERROR_I2C_INIT,
  ERROR_I2C_DIG_FLTR_CONFIG,
  ERROR_I2C_ANLG_FLTR_CONFIG,
  ERROR_LPTIM_INIT,
  ERROR_HAL_SAI_INIT,
  ERROR_USBD_INIT,
  ERROR_USBD_REGISTER_CLASS,
  ERROR_USBD_REGISTER_INTERFACE,
  ERROR_USBD_START,
  ERROR_USBD_SPEED_INIT,
  ERROR_USBD_OTG_INIT,
  ERROR_DMA_INIT,
  ERROR_UNKNOWN
} ErrorNum;

#endif
